<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>DreamTeam.Modules.Forms</RootNamespace>
		<AssemblyName>DreamTeam.Modules.Forms</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;CA1002;CA2227;S3267;S125</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
		<ProjectReference Include="..\Modules.Forms.Contracts\Modules.Forms.Contracts.csproj" />
	</ItemGroup>

</Project>
