<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
	    <RootNamespace>DreamTeam.Framework.Core</RootNamespace>
	    <AssemblyName>DreamTeam.Framework.Core</AssemblyName>
    </PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Mediator.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

</Project>
